# Generated by Django 4.2.3 on 2023-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold'), ('Bagel', 'Bagel')], db_index=True, default='others', max_length=14, verbose_name='Category'),
        ),
    ]
